### ISSUE TITLE
Support for Loading Presets

### ISSUE THREAD

**Issue by RobLaw0304** [joyfulhouse/WLED#2]
WLED-ESP32 allows for saving of 16 presets on the board.  There is an API command associated with each preset.
WLED-Hubitat could read the API command, extract the information for the LED segment it is set to care about, and apply that preset using the extracted information.

**Comment by cjrezz** [comment]
This would be great!

**Comment by btli** [comment]
You could just call the preset via JSON API by sending the ps value if I'm reading the documentation correctly. I don't have much free time to work on this, but if anyone wants to implement, happy to merge in the function.
