### ISSUE TITLE
Brightness bug

### ISSUE THREAD

**Issue by cjrezz** [joyfulhouse/WLED#4]
Seems to be a bug with setting the brightness. When LEDs are initially on full brightness then I adjust the brightness down through Hubitat, the WLED app doesn't reflect the new brightness as the brightness slider still shows it's at full brightness. However, the new lower brightness set by Hubitat becomes the max brightness in the WLED app and trying to increase the brightness won't increase the brightness level past the brightness set recently by Hubitat. 

The only way I can find to get the WLED app to reach it's full brightness again is to reboot WLED.

**Comment by btli** [comment]
With the latest WLED, it has two areas for brightness. A master brightness and the segment brightness. I have not had time to update the driver to support a parent/child device type, so the brightness being set is only at the segment level. If you wish for to control via the app, you can find this in the segments tab.

**Comment by cjrezz** [comment]
Oh that is good to know! Thank you for explaining that!
